### ISSUE TITLE
host + port settings if using laptop as server

### ISSUE THREAD

**Issue by svetlichnaya** [wearhere/spacecontrol#23]
Tried to get a test panel running last night (via the stacey_panel_test branch). Had the raspberry pi connected to my router via Ethernet and could ssh to it via static IP. Tried various ways of setting up  my laptop as the webserver but could only get to port 80 on the static IP. Will take another look later and try port forwarding. A bit more documentation around the CONTROLLER_IP param and how to use it with a port would be helpful cc @wearhere @jfslocum

**Comment by wearhere** [comment]
Ah it looks like the recent refactoring of the controller logic removed support for the environment variables @jfslocum. Compare https://github.com/wearhere/spacecontrol/commit/fae831d671703fc41365c910d59530393cd33045#diff-a7e11c32c1bae55cb019741a2ec8cd55L125 to https://github.com/wearhere/spacecontrol/blob/5102512/panels/panel_client.py#L216. Can fix later if no one else gets to it.

Not sure if that's the entirety of the problem or if you'll also need to expose port 8000 Stacey (the port on which the server communicates with the panels). That can also be overridden by an environment variable (when starting the server and panels) once https://github.com/wearhere/spacecontrol/commit/fae831d671703fc41365c910d59530393cd33045#diff-a7e11c32c1bae55cb019741a2ec8cd55L125 is reinstated, though I don't think port 80 will suffice, that port's usually for web traffic.
