### ISSUE TITLE
Call clear progress when game end or level end

### ISSUE THREAD

**Issue by dawnho** [wearhere/spacecontrol#56]
The way I implemented show progress requires calling {progress:0} when we need to clear the progress bar.

Guessing this will happen when a level ends, game ends, etc.

**Comment by wearhere** [comment]
The server clears the display by sending a set-status message with `data` = `{ message: '' }`, can you use that?

**Comment by wearhere** [comment]
Dawn clarifies that she is displaying the message and the progress separately. This is probably a good idea in the long term so that we can discuss statuses like "meteor incoming!" while the command progress continues to tick away.
