### ISSUE TITLE
game start

### ISSUE THREAD

**Issue by igor47** [wearhere/spacecontrol#9]
how do we start the game? this was discussed on the signal thread.

it makes sense to use the existing controls to indicate this. we all have buttons, we can use one to indicate to the server "this panel is opting into this game". any panel that's not opted in to the current game does not have it's controls selected for messaging.

how do we initiate a game, though? maybe one of the panels can be a "master" panel that has a control that can do that? and that panel has to be in use for every game?

**Comment by wearhere** [comment]
What I was thinking was:
1. When server boots, it's in "waiting for start" mode. In that mode, when panels connect to server, server tells each to display a command referencing a control _connected to that board_. (This differs from actual gameplay. See below for why that's important.)
2. The displays keep displaying these commands indefinitely until…
3. Someone walks up to a panel and performs the command. This means they're ready to play.
4. Now the server waits for 20-ish (TBD) seconds for people at other panels to perform those panels' commands.
5. At the end of those 20-ish seconds, whichever panels performed the command are players. The game now proceeds, only communicating with those panels.

Benefits:
* we don't need the server to have any controls of its own (at least for purposes of starting the game)
* panels don't need a special "start button"
* user demonstrates ability to play the game by performing a command (though if we have time it might be nice to provide more in-depth instructions)

**Comment by jfslocum** [comment]
Sounds good to me. Another benefit is it doesn't require any additional logic on the panels.
